# Generated by Django 5.0.6 on 2024-06-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('Version', models.CharField(max_length=250)),
            ],
        ),
    ]
