# Generated by Django 5.0.6 on 2024-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_nextmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextmodel',
            name='hotel_Main_Img',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
