# Generated by Django 5.0.6 on 2024-06-30 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_alter_nextmodel_hotel_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='nextmodel',
            name='hotel_Main_Img',
        ),
        migrations.AddField(
            model_name='nextmodel',
            name='censorcertificate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='censor', to='projectApp.censorinfo'),
        ),
    ]
