# Generated by Django 5.0.6 on 2024-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_dirinfo_nextmodel_dircertficate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='nextmodel',
            name='actor',
            field=models.ManyToManyField(null=True, related_name='actorsdetails', to='projectApp.actor'),
        ),
    ]
