# Generated by Django 5.0.6 on 2024-06-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0009_alter_nextmodel_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
