# Generated by Django 5.0.6 on 2024-07-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_actor_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discrption', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('priority', models.IntegerField(default=0)),
                ('delete_status', models.IntegerField(default=1, verbose_name=((1, 'Live'), (0, 'Delete')))),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='nextmodel',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='nextmodel',
            name='censorcertificate',
        ),
        migrations.DeleteModel(
            name='DetailModels',
        ),
        migrations.RemoveField(
            model_name='nextmodel',
            name='dircertficate',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='CensorInfo',
        ),
        migrations.DeleteModel(
            name='DirInfo',
        ),
        migrations.DeleteModel(
            name='NextModel',
        ),
    ]
